begin;
drop table if exists public.jobs cascade;
drop table if exists public.operation_log cascade;
drop table if exists public.versions cascade;
drop table if exists public.prompt_units cascade;
drop table if exists public.local_overrides cascade;
drop table if exists public.canon_state cascade;
drop table if exists public.rules cascade;
drop table if exists public."references" cascade;
drop table if exists public.links cascade;
drop table if exists public.story_units cascade;
drop table if exists public.entity_versions cascade;
drop table if exists public.entities cascade;
drop table if exists public.evidence cascade;
drop table if exists public.project_frames cascade;
drop table if exists public.projects cascade;
drop function if exists public.auto_create_canon_state() cascade;
drop function if exists public.mark_dependents_stale(text, uuid) cascade;
drop function if exists public.apply_prompt_regeneration(uuid, text) cascade;
commit;
